### ISSUE TITLE
Crash on Mod Load

### ISSUE THREAD

**Issue by buymytoasters** [shadowfacts/YeOldeTanks#10]
Crash on load. I tried two versions of Forge with no luck. I rolled back to the previous version of ye olde tanks with the same results.

http://pastebin.com/xpkG0Xiu
http://pastebin.com/VDhLc3BW

Mod looks great, and thank you for building it!

**Comment by shadowfacts** [comment]
Java 8 is required.

Edit: Also, your welcome :smile:

**Comment by buymytoasters** [comment]
Thanks Shadow!
