### ISSUE TITLE
More tank types

### ISSUE THREAD

**Issue by tlitookilakin** [shadowfacts/YeOldeTanks#11]
Namely higher capacity tanks, and a cosmetic variant that can be made to show a liquid but cannot actually contain anything.

**Comment by shadowfacts** [comment]
If the auto-output to the bottom option is enabled by the config (true by default), then multiple barrels can be stacked to function as 1 larger tank. How would the cosmetic barrels display the fluid? The same way they do now?

**Comment by tlitookilakin** [comment]
ideally, yes.
