### ISSUE TITLE
Crash on crafting barrel minecart (really any barrel-based recipe)

### ISSUE THREAD

**Issue by DaedalusGame** [shadowfacts/YeOldeTanks#12]
at net.shadowfacts.yeoldetanks.recipe.BarrelMinecartRecipe.java:

at line ~26, you're using the OpenComputers Item class to get an Item from a Block, causing a crash when OC is not installed.

**Comment by shadowfacts** [comment]
Goddamnit OpenComputers, not using mod specific names >.<

**Comment by shadowfacts** [comment]
1.2.0 hotfix has been uploaded to CurseForge.
