### ISSUE TITLE
put the tank in the ground, crashing (full and empty)

### ISSUE THREAD

**Issue by Sasikaa** [shadowfacts/YeOldeTanks#15]
Brief explanation of issue:
When put the tank in the ground (full AND empty) crashing my game.

Steps to reproduce:
- Crafting the tank.
- Put the tank in the ground, and crash

Link to crash report/log in a [gist](https://gist.github.com):
Not crash report...
x.1777 forge version, and FTB unstable 1.8 fresh modpack!

YeOldeTanks version:
YeOldeTanks-1.8.9-1.5.1.jar

Minecraft version:
What? XD (1.8.9?????)

**Comment by shadowfacts** [comment]
Please post the full fml-client-latest.log on [gist](https://gist.github.com).

**Comment by shadowfacts** [comment]
Closing because of no response.
