### ISSUE TITLE
1.9.4-1.7.0 crashes dedicated forge server 1.9.4 build 1921 on startup

### ISSUE THREAD

**Issue by kreezxil** [shadowfacts/YeOldeTanks#18]
Issue: yeoldetanks-1.9.4-1.7.0 crashes dedicated forge server 1.9.4 build 1921 on startup

crash report:
https://gist.github.com/e12ace861f3ebbe1acd75a86f71db3d6

fml server latest:
https://gist.github.com/cbb622c7d02ade96cb3aab1e2af4198a

**Comment by shadowfacts** [comment]
Will fix later today (hopefully). For now a workaround is to downgrade Forge.

**Comment by shadowfacts** [comment]
d2ecfa935d4388811ce41612717bb4394bae9842

1.7.1 is published to CurseForge and pending approval and has been published to the [Releases](https://github.com/shadowfacts/YeOldeTanks/releases) pages
