### ISSUE TITLE
[Bug] No crash, but useless barrels.

### ISSUE THREAD

**Issue by Dragnier** [shadowfacts/YeOldeTanks#19]
Brief explanation of issue: Put lava in a tank > pick up tank > re-place tank > no lava in tank > can no longer interact with tank to add or remove liquid (lava in this case). Also does not show how many mB current/max anymore after re-placing. Makes them completely useless. Here is a picture showing the dipping stick report 0mB / 0mB of Water in a barrel I broke and re-placed. [Ye Old Tanks Bug/Error](http://i.imgur.com/wvwD71q.png)

YeOldeTanks version: 1.7.1

Minecraft version: 1.9.4

**Comment by shadowfacts** [comment]
Unable to reproduce in 1.11.2
