### ISSUE TITLE
Placing Liquid DNA from Forestry/Binnies Mod in Barrel

### ISSUE THREAD

**Issue by DoughnutDev** [shadowfacts/YeOldeTanks#2]
I am using the latest of Ye Olde Tanks, Forestry and Binnies Mod and when I place the liquid DNA in a barrel it crashes. Here is the crash report. http://pastebin.com/xZFuzkAD

**Comment by shadowfacts** [comment]
Duplicate of #1. Update is coming shortly.

**Comment by shadowfacts** [comment]
[1.0.2](http://minecraft.curseforge.com/projects/ye-olde-tanks/files/22623010) has been uploaded to CF.
