### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by kzintiwife** [shadowfacts/YeOldeTanks#21]
Brief explanation of issue: getting a crash report. I had it running. Added additional mods, game crashed with the following error.  Tried removing those mods, added different mods. some worked, some added caused crash. 

Steps to reproduce:

- Step 1: add random mods and it crashes --- could get it to do it repeatedly with any 1 of the following
1. biomes o plenty 1.11.2-6.0.1.2145-universal
2. colors-1.11-1.0.0
3. grim pack-1.11.2-4.0.0.0-beta
4. pam's harvestCraft 1.11.2b

Link to crash report/log in a [gist](https://gist.github.com):
have 3 different ones with different mods. - have more if you want them :) 
[crash-2017-02-04_02.42.00-client.txt](https://github.com/shadowfacts/YeOldeTanks/files/752202/crash-2017-02-04_02.42.00-client.txt)
[crash-2017-02-04_02.52.15-client.txt](https://github.com/shadowfacts/YeOldeTanks/files/752200/crash-2017-02-04_02.52.15-client.txt)
[crash-2017-02-04_03.39.13-client.txt](https://github.com/shadowfacts/YeOldeTanks/files/752201/crash-2017-02-04_03.39.13-client.txt)

YeOldeTanks version: 1.11-1.9.1

Minecraft version: 1.11.2 (forge 1.11.2-13.20.0.2226)

edit:  crashes in forge loader at the 6/7 step.

**Comment by shadowfacts** [comment]
Fixed in YeOldeTanks [1.9.2](https://minecraft.curseforge.com/projects/ye-olde-tanks/files/2377761).
