### ISSUE TITLE
Barrels are completely useless

### ISSUE THREAD

**Issue by ScytheIronclaw** [shadowfacts/YeOldeTanks#23]
Brief explanation of issue: After crafting the barrels added by this mod and placing them down in-world, attempting to fill them with a bucket of water or lava does not work. Shift-Right-Clicking does not toggle the lid.

Steps to reproduce:

- Step 1 Download mod and craft a barrel
- Step 2 Place the barrel and attempt to empty a bucket into the barrel

Link to crash report/log in a [gist](https://gist.github.com):
[fml-client-latest.txt](https://github.com/shadowfacts/YeOldeTanks/files/773307/fml-client-latest.txt)

YeOldeTanks version: 1.11.2-1.9.3

Minecraft version: 1.11.2

Minecraft Forge Version:  13.20.0.2227

**Comment by shadowfacts** [comment]
Unable to reproduce, and there's nothing in the log that says anything's wrong.
