### ISSUE TITLE
Crash on Startup - Using 1.0.1

### ISSUE THREAD

**Issue by DoughnutDev** [shadowfacts/YeOldeTanks#3]
Relevant lines from the crashlog:

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: net.shadowfacts.yeoldetanks.YeOldeTanks

java.lang.UnsupportedClassVersionError: net/shadowfacts/yeoldetanks/YeOldeTanks : Unsupported major.minor version 52.0

Full log:
crash-2015-10-13_23.22.19-client.txt

**Comment by shadowfacts** [comment]
1. Java 8 is required.
2. o_O How'd you not get this crash before? /me is confused

**Comment by DoughnutDev** [comment]
Not my crash report, someone on my pack got this crash. Just passing it along.

**Comment by shadowfacts** [comment]
Heh, I was rather confused there.
